export const FETCH_ADDRESSES = 'FETCH_ADDRESS';
export const FETCH_ADDRESSES_FINISHED = 'FETCH_ADDRESSES_FINISHED';

export const SAVE_ADDRESS = 'SAVE_ADDRESS';
export const SAVE_ADDRESS_FINISHED = 'SAVE_ADDRESS_FINISHED';

export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const UPDATE_ADDRESS_FINISHED = 'UPDATE_ADDRESS_FINISHED';

export const SELECT_ADDRESS = 'SELECT_ADDRESS';