export const FETCH_ADDRESSES = 'FETCH_ADDRESS';
export const FETCH_ADDRESSES_FULFILLED = 'FETCH_ADDRESSES_FULFILLED';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const EDIT_ADDRESS = 'EDIT_ADDRESS';
