export const FETCH_ADDRESSES = 'FETCH_ADDRESS';
export const FETCH_ADDRESSES_FINISHED = 'FETCH_ADDRESSES_FINISHED';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const ADD_ADDRESS_FINISHED = 'ADD_ADDRESS_FINISHED';
export const EDIT_ADDRESS = 'EDIT_ADDRESS';
export const SELECT_ADDRESS = 'SELECT_ADDRESS';